/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: plaggy (https://sketchfab.com/plaggy)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cc0-toilet-paper-roll-6d5284b842434413a17133f7bf259669
title: CC0 - Toilet Paper Roll
*/

import React, { useRef } from 'react'

import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./scene.gltf');

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.03}>
          <group rotation={[-Math.PI / 2, 0, 0]}>
            <group position={[0, 0, -1.93]}>
              <mesh geometry={nodes.ToiletPaperRoll_ToiletPaperRoll_0.geometry} material={materials.ToiletPaperRoll} />
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
